# Generated by Django 2.0.3 on 2018-04-08 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clients',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='clients',
            name='last_name',
        ),
    ]
