# Generated by Django 2.0.3 on 2018-04-09 21:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('db', '0002_auto_20180408_2021'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_account_no', models.IntegerField()),
                ('to_account_no', models.IntegerField()),
                ('time', models.DateTimeField()),
                ('amount', models.FloatField()),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='clients',
            name='clients_id',
        ),
        migrations.RemoveField(
            model_name='account',
            name='id',
        ),
        migrations.AlterField(
            model_name='account',
            name='acc_balance',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='account',
            name='acc_no',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='loan',
            name='loan_amount',
            field=models.FloatField(),
        ),
        migrations.DeleteModel(
            name='Clients',
        ),
    ]
