# Generated by Django 2.0.3 on 2018-04-10 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_auto_20180410_0323'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='loan_type',
        ),
    ]
